FROM node:18

WORKDIR /app/frontend/vite-project

COPY frontend/vite-project/package.json frontend/vite-project/package-lock.json ./
RUN npm install

COPY frontend/vite-project/ .

CMD ["npm", "run", "dev"]